package armstrong.navigation;

public enum ParticleType {
	OPPOSITE_ARCHON, OPPOSITE_GUARD, OPPOSITE_SOLDIER, OPPOSITE_VIPER, OPPOSITE_SCOUT, OPPOSITE_TURRET, ALLY_TURRET, ALLY_ARCHON, FIGHTING_ALLY, ZOMBIE, DEN
}
